import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { Pool } from 'pg';
import OpenAI from 'openai';
import { z } from 'zod';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const app=express(); const port=Number(process.env.PORT||10000); const databaseUrl=process.env.DATABASE_URL||'';
const useDb=/^postgres(ql)?:\/\//i.test(databaseUrl)&&!databaseUrl.includes('PLACEHOLDER');
const pool=useDb?new Pool({connectionString:databaseUrl,ssl:{rejectUnauthorized:false}}):null;
const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const __dirname=path.dirname(fileURLToPath(import.meta.url));
app.use(helmet({contentSecurityPolicy:false})); app.use(cors({origin:process.env.CORS_ORIGIN||'*'})); app.use(express.json({limit:'32kb'}));

type Event={type:string;title:string;description:string;actor:string;createdAt:string};
const project={id:1,name:'VoicePilot',repository:'aithavignesh/voicepilot-as03',description:'Voice-first AI engineering copilot that lets developers talk to a project instead of navigating dashboards.',stack:['TypeScript','Node.js','Express','PostgreSQL','OpenAI','Web Speech API'],status:'healthy',healthScore:96,updatedAt:new Date().toISOString()};
const files=[
{path:'src/server.ts',language:'TypeScript',sizeBytes:17000,risk:'medium',summary:'API, command routing, intent/entity extraction and AI orchestration.'},
{path:'public/app.js',language:'JavaScript',sizeBytes:15000,risk:'medium',summary:'Voice capture, command console, speech output and live dashboard.'},
{path:'schema.sql',language:'SQL',sizeBytes:6500,risk:'low',summary:'Persistent project, health, events, conversations and message tables.'},
{path:'public/index.html',language:'HTML',sizeBytes:13000,risk:'low',summary:'Voice-first engineering cockpit interface.'},
{path:'public/styles.css',language:'CSS',sizeBytes:12000,risk:'low',summary:'Responsive dark technical dashboard styling.'},
{path:'package.json',language:'JSON',sizeBytes:1400,risk:'medium',summary:'Runtime, AI, validation and PostgreSQL dependencies.'}];
let health=[
{name:'TypeScript',status:'passing',score:100,detail:'Strict type checks configured.'},{name:'API',status:'passing',score:98,detail:'Project, voice, command and insight routes available.'},{name:'Database',status:useDb?'passing':'demo-mode',score:useDb?97:92,detail:useDb?'PostgreSQL persistence is connected.':'Safe demo mode; add DATABASE_URL for persistence.'},{name:'Dependencies',status:'warning',score:88,detail:'Review dependency updates before production.'},{name:'Security',status:'passing',score:95,detail:'Helmet, validation and bounded inputs enabled.'},{name:'Voice pipeline',status:'passing',score:96,detail:'Speech recognition → intent → entity → command/answer → speech output.'}];
let events:Event[]=[
{type:'deploy',title:'Deployment prepared',description:'Render deployment configuration verified.',actor:'VoicePilot',createdAt:new Date(Date.now()-20*60000).toISOString()},
{type:'feature',title:'Command execution layer',description:'Safe read-only project commands can be triggered by natural language.',actor:'VoicePilot',createdAt:new Date(Date.now()-40*60000).toISOString()},
{type:'test',title:'API checks passed',description:'Voice command, project and intelligence routes are ready.',actor:'CI',createdAt:new Date(Date.now()-55*60000).toISOString()},
{type:'feature',title:'Intent + entity extraction',description:'Natural language commands map to project intents and entities.',actor:'VoicePilot',createdAt:new Date(Date.now()-95*60000).toISOString()},
{type:'scan',title:'Security baseline checked',description:'Request validation and security headers reviewed.',actor:'VoicePilot',createdAt:new Date(Date.now()-140*60000).toISOString()}];
const conversations=new Map<string,{role:string;content:string;metadata?:any;createdAt:string}[]>();
const clean=(s:string)=>s.replace(/[<>]/g,'').trim().slice(0,1200);
const intentFor=(text:string)=>{const t=text.toLowerCase();let intent='project_snapshot';if(/health|healthy|test|security|risk|issue|warning|status/.test(t))intent='health_report';else if(/change|recent|activity|commit|deploy|what happened|latest/.test(t))intent='recent_activity';else if(/architecture|stack|technology|files|structure|how is it built/.test(t))intent='architecture';else if(/scan|check project|run check/.test(t))intent='run_health_scan';else if(/recommend|next|fix|improve|priorit|should i/.test(t))intent='recommendation';else if(/file|open|show/.test(t))intent='file_lookup';const entities=[...new Set((t.match(/\b(?:health|security|database|api|frontend|backend|typescript|postgresql|deployment|dependency|voice|architecture|activity|github|commit)\b/g)||[]))];return{intent,entities};};
const fallback=(text:string,p:any)=>{if(p.intent==='health_report')return`VoicePilot health is ${project.healthScore}/100. ${health.map(x=>`${x.name}: ${x.status} (${x.score}%)`).join('; ')}. The only warning is dependency freshness.`;if(p.intent==='recent_activity')return`Recent repository activity is available from GitHub. The dashboard shows the latest commits when the public repository API is reachable, with a safe demo fallback if it is not.`;if(p.intent==='architecture')return`The flow is browser voice capture → command API → intent and entity extraction → grounded project context → deterministic action or AI answer → speech output. PostgreSQL is supported for persistence.`;if(p.intent==='run_health_scan')return`I can run the project's safe health scan now. It checks the configured project baseline and refreshes the dashboard.`;if(p.intent==='recommendation')return`Priority one is dependency hardening. Next, connect PostgreSQL for persistent conversations, then keep repository events live through GitHub.`;if(p.intent==='file_lookup')return`Files to watch: ${files.filter(x=>x.risk!=='low').map(x=>x.path).join(', ')}. I can explain what each file does.`;return`${project.name} is a ${project.description} Stack: ${project.stack.join(', ')}. Health is ${project.healthScore}/100. Ask about health, architecture, activity, risky files, or what to fix next.`;};

async function githubActivity(limit=8):Promise<Event[]>{
  try{
    const safeLimit=Math.min(Math.max(limit,1),10);
    const r=await fetch(`https://api.github.com/repos/${project.repository}/commits?per_page=${safeLimit}`,{headers:{accept:'application/vnd.github+json','user-agent':'VoicePilot-AS03'}});
    if(!r.ok) return events.slice(0,safeLimit);
    const data=await r.json() as any[];
    if(!Array.isArray(data)||!data.length) return events.slice(0,safeLimit);
    return data.map(c=>({type:'github',title:c.commit?.message?.split('\n')[0]?.slice(0,90)||'GitHub commit',description:`${c.sha?.slice(0,7)||'commit'} · ${c.commit?.author?.name||c.author?.login||'repository contributor'}`,actor:c.author?.login||c.commit?.author?.name||'GitHub',createdAt:c.commit?.author?.date||new Date().toISOString()}));
  }catch{return events.slice(0,limit);}
}

async function answerFor(text:string){const p=intentFor(text);let answer=fallback(text,p),source='grounded-demo';if(p.intent==='recent_activity'){const live=await githubActivity(5);answer=`Latest repository activity: ${live.map(x=>`${x.title} (${x.createdAt.slice(0,10)})`).join('; ')}.`;source=live[0]?.type==='github'?'github':'grounded-demo';}if(openai){try{const liveEvents=p.intent==='recent_activity'?await githubActivity(8):events.slice(0,8);const r=await openai.chat.completions.create({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',temperature:.2,messages:[{role:'system',content:'You are VoicePilot, a voice-first engineering copilot. Use only supplied project facts. Never fabricate. Be concise. Separate facts from recommendations. Never claim an action ran unless the action result says it ran.'},{role:'user',content:JSON.stringify({request:text,intent:p,project,health,events:liveEvents,files})}]});answer=r.choices[0]?.message?.content?.trim()||answer;source='openai';}catch{}}return{answer,intent:p.intent,entities:p.entities,source};}
async function runCommand(text:string){const p=intentFor(text);if(p.intent==='run_health_scan'){project.updatedAt=new Date().toISOString();const result={ok:true,action:'health_scan',score:project.healthScore,message:`Health scan completed. Score: ${project.healthScore}/100.`};events.unshift({type:'scan',title:'Voice-triggered health scan',description:result.message,actor:'VoicePilot',createdAt:project.updatedAt});return{...result,intent:p.intent,entities:p.entities};}const d=await answerFor(text);return{ok:true,action:'answer',message:d.answer,intent:d.intent,entities:d.entities};}

app.get('/api/health',async(_req,res)=>{if(pool){try{await pool.query('SELECT 1');}catch{return res.status(503).json({ok:false});}}res.json({ok:true,service:'voicepilot',ai:!!openai,database:useDb,mode:useDb?'postgres':'demo'});});
app.get('/api/project',(_req,res)=>res.json(project)); app.get('/api/project/files',(_req,res)=>res.json(files)); app.get('/api/project/health',(_req,res)=>res.json({score:project.healthScore,checks:health}));
app.get('/api/project/activity',async(req,res)=>{const n=Math.min(Math.max(Number(req.query.limit)||8,1),20);res.json(await githubActivity(n));});
app.get('/api/project/repository',async(_req,res)=>{try{const r=await fetch(`https://api.github.com/repos/${project.repository}`,{headers:{accept:'application/vnd.github+json','user-agent':'VoicePilot-AS03'}});if(!r.ok)return res.status(502).json({ok:false,source:'github'});const d=await r.json() as any;res.json({ok:true,source:'github',name:d.full_name,description:d.description,defaultBranch:d.default_branch,stars:d.stargazers_count,forks:d.forks_count,openIssues:d.open_issues_count,language:d.language,pushedAt:d.pushed_at,updatedAt:d.updated_at});}catch{res.status(503).json({ok:false,source:'github'});}});
app.get('/api/project/insights',(_req,res)=>res.json({risk:files.filter(x=>x.risk!=='low').map(x=>({path:x.path,risk:x.risk,reason:x.summary})),priorities:[{rank:1,title:'Harden dependencies',detail:'Review the dependency warning before production.'},{rank:2,title:'Connect PostgreSQL',detail:useDb?'Persistence is connected.':'Add DATABASE_URL to persist conversations and project events.'},{rank:3,title:'Keep repository events live',detail:'VoicePilot now reads public GitHub commit activity with a safe fallback.'}],capabilities:['Voice questions','Intent detection','Entity extraction','Safe command execution','Health scanning','Risk analysis','Architecture explanation','Conversation memory','GitHub repository activity','Text-to-speech']}));
app.post('/api/project/scan',(_req,res)=>{project.updatedAt=new Date().toISOString();events.unshift({type:'scan',title:'Health scan completed',description:'VoicePilot rechecked its project baseline.',actor:'VoicePilot',createdAt:project.updatedAt});res.json({ok:true,score:project.healthScore});});
app.post('/api/voice/command',async(req,res)=>{try{const text=clean(z.string().min(2).max(1200).parse(req.body?.text));if(intentFor(text).intent==='run_health_scan')return res.json(await runCommand(text));res.json(await answerFor(text));}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Invalid request'});}});
app.post('/api/commands/execute',async(req,res)=>{try{const text=clean(z.string().min(2).max(1200).parse(req.body?.text));res.json(await runCommand(text));}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Invalid request'});}});
app.post('/api/conversations',async(_req,res)=>{if(pool){try{const r=await pool.query('INSERT INTO conversations(project_id) VALUES($1) RETURNING id',[1]);return res.json({conversationId:r.rows[0].id,persistent:true});}catch{}}const id=crypto.randomUUID();conversations.set(id,[]);res.json({conversationId:id,persistent:false});});
app.get('/api/conversations/:id/messages',async(req,res)=>{if(pool){try{const r=await pool.query('SELECT role,content,metadata,created_at AS "createdAt" FROM messages WHERE conversation_id=$1 ORDER BY created_at',[req.params.id]);return res.json(r.rows);}catch{}}res.json(conversations.get(req.params.id)||[]);});
app.post('/api/conversations/:id/messages',async(req,res)=>{try{const text=clean(z.string().min(2).max(1200).parse(req.body?.text));const d=await answerFor(text);const now=new Date().toISOString();if(pool){try{await pool.query('INSERT INTO messages(conversation_id,role,content,metadata) VALUES($1,$2,$3,$4),($1,$5,$6,$7)',[req.params.id,'user',text,{},'assistant',d.answer,JSON.stringify({intent:d.intent,entities:d.entities,source:d.source})]);return res.json(d);}catch{}}if(!conversations.has(req.params.id))conversations.set(req.params.id,[]);const list=conversations.get(req.params.id)!;list.push({role:'user',content:text,createdAt:now},{role:'assistant',content:d.answer,metadata:{intent:d.intent,entities:d.entities,source:d.source},createdAt:new Date().toISOString()});res.json(d);}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Invalid request'});}});
app.use(express.static(path.join(__dirname,'../public')));app.use((_req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));app.listen(port,()=>console.log(`VoicePilot listening on ${port} | mode=${useDb?'postgres':'demo'} | ai=${!!openai}`));